<?php
	echo $header;
?>
<div class="container">
	<ul class="breadcrumb">
		<?php
			foreach($breadcrumbs as $breadcrumb)
			{	?>
				<li>
					<a href="<?php echo $breadcrumb['href']; ?>">
						<?php echo $breadcrumb['text']; ?>
					</a>
				</li>
				<?php
			}
		?>
	</ul>
	<div class="row">
		<div id="content" class="col-md-12 important-text ">
			<div class="common-content edit_account row">
<p>Términos y condiciones.<br>
  <br>
  Este contrato  describe los términos y condiciones generales (los &quot;términos y condiciones  generales&quot;) aplicables al uso de los servicios ofrecidos por porcantidad  s.a&nbsp; (&quot;los servicios&quot;) dentro  de los sitios <a href="http://www.xcantidad.com">www.xcantidad.com</a> y <a href="http://www.xcantidad.com.ar">www.xcantidad.com.ar</a> cualquier persona (en adelante  &quot;usuario&quot; o en plural &quot;usuarios&quot;) que desee acceder y/o  usar el sitio o los servicios podrá hacerlo sujetándose a los términos y  condiciones generales respectivos, junto con todas las demás políticas y  principios que rigen porcantidad y que son incorporados al presente por  referencia.<br>
  Cualquier persona que no acepte estos términos y condiciones generales, los  cuales tienen un carácter obligatorio y vinculante, deberá abstenerse de  utilizar el sitio y/o los servicios.<br>
  Porcantidad s.a se reserva el derecho de actualizar las presentes condiciones  en cualquier momento. El usuario entiende y conviene en que es el único  responsable de revisar las condiciones periódicamente.<br>
  El uso del sitio y/o sus servicios implica la aceptación de estos términos y  condiciones generales de uso de porcantidad.<br>
  El usuario debe leer, entender y aceptar todas las condiciones establecidas en  los términos y condiciones generales y en las políticas de privacidad así como  en los demás documentos incorporados a los mismos por referencia, previo a su  registración como usuario de porcantidad.com</p>
<ol>
  <li> Exención de garantías</li>
</ol>
<p>El usuario  expresamente conviene en que el uso del sitio porcantidad y los servicios  tendrán lugar exclusivamente bajo su responsabilidad. El sitio porcantidad y el  servicio se proporcionan en una base &quot;como es&quot; o bien &quot;como se  encuentra disponible&quot;, sin garantía alguna. Dentro del alcance permitido por  la ley, se exime a porcantidad, sus oficiales, directores, empleados, y agentes  de toda garantía, expresa o implícita, en conexión con el sitio web y su uso.  Porcantidad no garantiza ni representa la certeza, exactitud o puntualidad del  contenido del sitio, o de los sitios o el servicio accedido a través de los  enlaces en el sitio porcantidad y no asume responsabilidad alguna por (i)  errores, imprecisiones, del contenido, (ii) daño personal o daño a propiedades,  o daño de cualquier naturaleza que resulte de su acceso y/o uso del sitio (iii)  acceso y/o uso sin autorización de nuestros servidores seguros y/o a cualquier  información personal y/o financiera almacenada en los mismos (iv) cualquier  interrupción o cesación de transmisión desde o hacia el sitio (v) cualquier  falla, virus, troyano o similar que pueda ser transmitido desde o a través de  nuestro sitio por un tercero, y/o (vi) cualquier error u omisión en el  contenido o por cualquier pérdida o daño de cualquier tipo en el cual se haya  incurrido como resultado del uso del contenido posteado en el sitio, email  enviado a través del sitio, transmitido o hecho disponible a través de nuestro  sitio. Porcantidad no garantiza, ni se adhiere, ni asume responsabilidad por  ningún producto, o servicio publicitado u ofrecido por un tercero a través de  porcantidad o de los sitios accedido a través de los enlaces en el sitio  porcantidad, o que aparezcan publicitados en cualquier cartel o imagen dentro  del sitio, y porcantidad no será participe ni en ninguna forma responsable de  monitorear ningún transacción entre usted y un tercero que ofrezca productos o  servicios. Ni con la compra de un producto o servicio a través de cualquier  medio o en cualquier circunstancia, usted debería usar su mejor criterio y  ejercitar precaución en caso de ser necesario. </p>
<ol>
  <li>Limitación de la responsabilidad</li>
</ol>
<p>En ningún caso  porcantidad será responsable por daños y perjuicios directos, indirectos,  imprevistos, mediatos o punitorios (incluso si porcantidad  fue advertido sobre dichos daños y perjuicios),  que resulten de algún aspecto del uso que el usuario haga del sitio o el  servicio de porcantidad , ya sea que los daños y perjuicios surjan a partir del  uso o el mal uso del sitio o el servicio de porcantidad , ante la incapacidad  de utilizar el sitio o el servicio de porcantidad , o la interrupción,  suspensión, modificación, alteración o cancelación del sitio o el servicio  porcantidad. Dicha limitación también será aplicable con relación a los daños y  perjuicios en que se incurran a raíz de otros servicios o productos recibidos a  través o publicados con relación al sitio o al servicio de porcantidad o los  enlaces en el sitio de porcantidad, así como también a causa de la información  o el consejo recibido a través del sitio o del servicio porcantidad o  publicitado con relación a estos o uno de los enlaces en el sitio porcantidad  las limitaciones que anteceden se aplicarán dentro del máximo alcance permitido  por la ley. Usted específicamente reconoce que porcantidad no será responsable  por contenido publicado por usuarios, ni tampoco de la conducta ofensiva,  difamatoria o ilegal de ningún tercero y que el riesgo de daño del precedente  recae totalmente en usted.</p>
<ol>
  <li>Conducta</li>
</ol>
<p>El usuario acepta no  anunciar, enviar por email ni de cualquier otra forma poner a disposición  contenido que:<a name="_GoBack"></a><br>
  Sea contrario a la ley, viole una patente, marca registrada, secreto comercial,  derecho de autor u otro derecho de propiedad de cualquier persona, o contenido  respecto del cual el usuario no tiene derecho a poner a disposición del público  conforme a una disposición legal, una relación contractual o fiduciaria. Sea  dañino, ilícito, amenazador, abusivo, acosador, difamatorio, contenidos para  adultos, prostitución, pornográfico, pedofilia, relacionado con juegos de azar,  difamatorio, que invada la privacidad de otros o que dañe a menores de  cualquier forma; acose, degrade, intimide o sea odioso respecto a un individuo  o un grupo de individuos por su religión, género, orientación sexual, raza,  etnia, edad o discapacidad; imite a otra persona o entidad, incluyendo un  empleado, representante o agente de porcantidad , o que implique una falsa  declaración o que de cualquier manera tergiverse la relación del usuario con  una persona o con una entidad; incluya información personal o de identificación  de otra persona, sin el consentimiento expreso de la persona mencionada; sea  falso, engañoso, de una falsa apariencia, tramposo, engañe respecto de la  información o que constituya una forma de &quot;atracción y luego se modifique  lo ofrecido&quot;;constituya o contiene &quot;marketing afiliado&quot;, un  &quot;código de referencia a enlace&quot;, &quot;mail basura&quot;,  &quot;spam&quot;, &quot;cadenas de cartas&quot;, &quot;esquemas de  pirámides&quot; o publicidad comercial no solicitada. Constituya o bien contenga  cualquier forma de publicidad o promoción si (1) se publica en áreas o en  categorías de los sitios de porcantidad que no están diseñados para dicha  finalidad; o (2) enviado por email a los usuarios de porcantidad que  solicitaron no ser contactados con relación a otros servicios, productos o  intereses comerciales. Incluya enlaces a servicios comerciales o a sitios en la  web, salvo lo específicamente permitido por porcantidad; publicita servicios  ilícitos o la venta de artículos cuya venta se encuentra prohibida o  restringida por la ley aplicable según el caso; contiene virus de software u  otros códigos, archivos o programas de computación diseñados para interrumpir,  destruir o limitar la funcionalidad de un software o de un hardware de  computación o de un equipo de telecomunicaciones; interrumpa el flujo normal del  diálogo con una cantidad excesiva de mensajes (ataque masivo) al servicio, que  de alguna forma afecta en forma negativa la capacidad de los usuarios para  utilizar el servicio; utilice direcciones de email confusas, o encabezados  falsos o que de otra forma manipula los identificadores a fin de ocultar el  origen del contenido transmitido a través del servicio.<br>
  Sumado a ello, el usuario conviene en: no contactar a las personas que  solicitaron no ser contactadas; no &quot;acechar&quot; o de otra forma acosar a  otros; no recolectar datos personales sobre otros usuarios con fines  comerciales o contrarios a la ley; no utilizar medios automáticos, con  inclusión de arañas, robots, rastreadores, herramientas de ataque a datos, o  similares para descargar información del servicio o del sitio, salvo los  motores de búsqueda de internet (por ejemplo, google) y archivos públicos no  comerciales .no anunciar contenido que no sea local o que por otro motivo  carezca de relevancia, publicar un mismo contenido o contenido similar en repetidas  oportunidades, o de otra forma imponer una carga no razonable o  desproporcionada en nuestra infraestructura; no anunciar un mismo artículo o  servicio en más de una categoría de clasificación o foro, en más de un área  metropolitana; o no intentar obtener acceso sin autorización a los sistemas de  computación de porcantidad o bien dedicarse a una actividad que interrumpa,  baje la calidad, interfiera con el desempeño o deteriore la funcionalidad del  servicio o del sitio web de porcantidad. No realizar actividades ilegales según  la legislación que resulte aplicable en el caso concreto.</p>
<ol>
  <li>Capacidad</li>
</ol>
<p>Los servicios sólo  están disponibles para personas que tengan capacidad legal para contratar. No  podrán utilizar los servicios las personas que no tengan esa capacidad, los  menores de edad o usuarios de porcantidad que hayan sido suspendidos  temporalmente o inhabilitados definitivamente. Si estás registrando un usuario  como empresa, debes tener capacidad para contratar a nombre de tal entidad y de  obligar a la misma en los términos de este acuerdo.</p>
<ol>
  <li>Política de privacidad y  divulgación de información</li>
</ol>
<p>Mediante el uso del  sitio web, el usuario reconoce y conviene en que porcantidad puede a su sola  discreción conservar por tiempo indeterminado o divulgar el contenido del usuario,  así como también su información, ya sea direcciones de email, direcciones ip,  datos de tiempo y hora, y demás información del usuario, sobre sus actividades  o acceso y uso del sitio, siempre que considere que es necesario por ley o  creyendo de buena fe que dicha conservación o divulgación es razonablemente  necesaria para lo siguiente: cumplir con un proceso legal; exigir el  cumplimiento de estas condiciones; responder a reclamos sobre la violación de  los derechos de terceros en virtud del contenido; responder reclamos de que  información de contacto (por ejemplo, número telefónico, domicilio, calle) de  un tercero fue anunciada o transmitida sin su consentimiento o como una forma  de acoso; proteger los derechos, la propiedad, o la seguridad personal de  porcantidad, sus usuarios o del público en general.</p>
<ol>
  <li>. Publicación de bienes y/o  servicios.</li>
</ol>
<p>El usuario deberá  ofrecer a la venta los bienes y promover los servicios en las categorías y  subcategorizas apropiadas. Las publicaciones podrán incluir textos descriptivos,  gráficos, fotografías y otros contenidos y condiciones pertinentes para la  venta del bien o la promoción del servicio, siempre que no violen ninguna  disposición de este acuerdo o demás políticas de porcantidad. El producto  ofrecido por el usuario vendedor debe ser exactamente descrito en cuanto a sus  condiciones y características relevantes. Se entiende y presume que mediante la  inclusión del bien o servicio en porcantidad , el usuario acepta que tiene la  intención y el derecho de vender el bien por él ofrecido, o está facultado para  ello por su titular y lo tiene disponible para su entrega inmediata. Se  establece que los precios de los productos publicados deberán ser expresados  con IVA incluido cuando corresponda la aplicación del mismo, y en moneda del  curso legal. Porcantidad podrá remover cualquier publicación cuyo precio no sea  expresado de esta forma para evitar confusiones o malos entendidos en cuanto al  precio final del producto. Se deja expresamente establecido que ninguna  descripción podrá contener datos personales o de contacto, tales como, y sin  limitarse a, números telefónicos, dirección de e-mail, dirección postal,  direcciones de páginas de internet que contengan datos como los mencionados  anteriormente. En caso que se infrinja cualquiera de las disposiciones  establecidas en esta cláusula, porcantidad podrá editar el espacio, solicitar  al usuario que lo edite, o dar de baja la publicación donde se encuentre la  infracción.</p>
<ol>
  <li>. Inclusión de imágenes y  fotografías</li>
</ol>
<p>El usuario puede  incluir imágenes y fotografías del producto ofrecido siempre que las mismas se  correspondan con el artículo, salvo que se trate de bienes o productos o de  servicios que por su naturaleza no permiten esa correspondencia.<br>
  Porcantidad podrá impedir la publicación de la fotografía, e incluso del  producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con  los presentes términos y condiciones.</p>
<ol>
  <li>. Artículos prohibidos</li>
</ol>
<p>Sólo podrán ser  ingresados en las listas de bienes ofrecido y/o servicios promocionados,  aquellos cuya venta no se encuentre tácita o expresamente prohibida en los  términos y condiciones generales y demás políticas de porcantidad o por la ley  vigente.</p>
<ol>
  <li>Derechos de propiedad</li>
</ol>
<p>El servicio se  encuentra protegido dentro del máximo alcance permitido por las leyes y los  tratados internacionales respecto a los derechos de autor. El contenido que se  muestra en el servicio o a través del servicio, se encuentra protegido por las  leyes de derecho de autor como trabajo colectivo y/o compilación, conforme a  las leyes de derecho de autor y a los convenios internacionales al respecto.  Queda prohibido reproducir, modificar, crear trabajos derivados o bien  redistribuir los sitios o el trabajo colectivo. Queda prohibido copiar o  reproducir los sitios o partes de estos en otro servidor o ubicación para su  subsiguiente reproducción o redistribución. El usuario se obliga además a no  reproducir, duplicar ni copiar contenido del servicio incluyendo los avisos, la  estructura y organización del sitio y el código informático. Asimismo, conviene  en someterse a todas las notificaciones de derechos de autor que se publican en  el servicio. El usuario no puede descompilar o desensamblar o aplicar  ingeniería inversa o de otra manera intentar descubrir los códigos fuente que  pudieran encontrarse en el servicio. El usuario se obliga a no reproducir,  duplicar, copiar, vender, revender ni explotar con fines comerciales ningún  aspecto del servicio. Porcantidad es una marca registrada ante la oficina de  patentes y marcas de la república argentina. Si bien porcantidad no reclama  titularidad sobre el contenido publicado por sus usuarios, al anunciar  contenido en las áreas públicas del servicio, el usuario automáticamente  otorga, manifiesta y garantiza que él cuenta con el derecho de otorgar a favor  de porcantidad una licencia irrevocable, vitalicia, no-exclusiva, totalmente  paga y de alcance mundial para usar, copiar, ejecutar, desplegar y distribuir  dicho contenido y para preparar trabajos derivados a partir de este o bien  incorporarlo en otros trabajos, y otorgar y autorizar sub-licencias (a través  de múltiples escalafones) de lo que antecede. Necesitamos contar con estos  derechos para albergar y desplegar el contenido de usuario.</p>
<ol>
  <li>Derechos de propiedad intelectual</li>
</ol>
<p>El material presente  en el sitio de porcantidad , con excepción del material que ha sido posteado  por nuestros usuarios  , incluyendo sin  limitación, el texto, software, scripts, gráficos, fotos, sonidos, música,  videos, funciones interactivas y cosas similares (&ldquo;materiales&rdquo;) y las marcas  registradas, marcas del servicio y logotipos contenidos en el mismo (&ldquo;marcas&rdquo;),  son propiedad o han sido licenciadas a porcantidad , y están sujetas a los  derechos de propiedad intelectual. Los materiales contenidos en porcantidad son  provistos a usted para su información y uso personal solamente y no puede ser  usada, copiada, reproducida, distribuida, transmitida, exhibida, vendida,  licenciada, o explotada de cualquier otra forma para ningún otro fin, sin el  previo permiso escrito de sus respectivos dueños. Porcantidad se reserva todo  derecho no expresamente dado en y para el sitio y los materiales. Usted acepta  no involucrarse en el uso, copia, o distribución de cualquiera de los  materiales a no ser que sea expresamente permitido acá, incluyendo el uso,  copia, o distribución de contenido publicado por usuarios sobre terceros  obtenido a través del sitio para cualquier fin comercial. Si usted descarga o  imprime una copia de los materiales para uso personal, usted debe retener toda  marca registrada y otras notificaciones de propiedad contenidas aquí. Usted  acepta no burlar, deshabilitar, o interferir con ninguna función de seguridad  del sitio de porcantidad ni tampoco con funciones que previenen o restringen el  uso, o el copiado de los materiales o que imponen limitaciones en el uso del  sitio de porcantidad o de los materiales contenidos ahí.</p>
<ol>
  <li>Privacidad de la información.</li>
</ol>
<p>Para utilizar los  servicios ofrecidos por porcantidad, los usuarios deberán facilitar  determinados datos de carácter personal. Su información personal se procesa y  almacena en servidores con estándares de seguridad y protección tanto física  como tecnológica.</p>
<ol>
  <li>Responsabilidad</li>
</ol>
<p>Porcantidad sólo  pone a disposición de los usuarios un espacio virtual que les permite ponerse  en comunicación mediante internet para encontrar una forma de vender o comprar  servicios o bienes. Porcantidad no es el propietario de los artículos  ofrecidos, no tiene posesión de ellos ni los ofrece en venta. Porcantidad no  interviene en el perfeccionamiento de las operaciones realizadas entre los  usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello  no será responsable respecto de la existencia, calidad, cantidad, estado,  integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por  los usuarios, así como de la capacidad para contratar de los usuarios o de la  veracidad de los datos personales por ellos ingresados. Cada usuario conoce y  acepta ser el exclusivo responsable por los artículos que publica para su venta  y por las ofertas y/o compras que realiza.<br>
  Debido a que porcantidad no tiene ninguna participación durante todo el tiempo  en que el artículo se publica para la venta, ni en la posterior negociación y  perfeccionamiento del contrato definitivo entre las partes, no será responsable  por el efectivo cumplimiento de las obligaciones asumidas por los usuarios en  el perfeccionamiento de la operación. El usuario conoce y acepta que al  realizar operaciones con otros usuarios o terceros lo hace bajo su propio  riesgo. En ningún caso porcantidad será responsable por lucro cesante, o por  cualquier otro daño y/o perjuicio que haya podido sufrir el usuario, debido a  las operaciones realizadas o no realizadas por artículos publicados a través de  porcantidad.<br>
  Porcantidad recomienda actuar con prudencia y sentido común al momento de  realizar operaciones con otros usuarios. El usuario debe tener presentes,  además, los riesgos de contratar con menores o con personas que se valgan de  una identidad falsa. Porcantidad no será responsable por la realización de  ofertas y/o operaciones con otros usuarios basadas en la confianza depositada  en el sistema o los servicios brindados por porcantidad.<br>
  En caso que uno o más usuarios o algún tercero inicien cualquier tipo de  reclamo o acciones legales contra otro u otros usuarios, todos y cada uno de  los usuarios involucrados en dichos reclamos o acciones eximen de toda  responsabilidad a porcantidad y a sus directores, gerentes, empleados, agentes,  operarios, representantes y apoderados. <br>
  En virtud que el usuario vendedor tiene la facultad para eliminar preguntas o  impedir a un usuario hacer preguntas u ofertas en sus publicaciones, se deja  aclarado que en ese caso, el usuario será el exclusivo responsable por esa  decisión y las consecuencias que pudieran acarrear.</p>
<ol>
  <li>Publicaciones de usuarios</li>
</ol>
<p>Usted entiende que  al usar porcantidad , usted quedará expuesto a contenido proveniente de  variadas fuentes, y que porcantidad  no  es responsable de la exactitud, utilidad, seguridad o de los derechos de  propiedad intelectual de o relacionados con dicho contenido. Usted además  entiende y acepta que usted puede exponerse a contenido que puede ser  impreciso, ofensivo, indecente o cuestionable, y que usted acepta a renunciar a  cualquier derecho legal o derecho equitativo o remedios que puede o puede  llegar a tener contra porcantidad con respecto a eso.</p>
<ol>
  <li>Violaciones al sistema y base de  datos</li>
</ol>
<p>No está permitida  ninguna acción o uso de dispositivo, software, u otro medio tendiente a  interferir tanto en las actividades y operatoria de porcantidad como en las  ofertas, descripciones, cuentas o bases de datos de porcantidad. Cualquier  intromisión, tentativa o actividad violatoria o contraria a las leyes sobre  derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este  contrato harán pasible a su responsable de las acciones legales pertinentes, y  a las sanciones previstas por este acuerdo, así como lo hará responsable de  indemnizar los daños ocasionados.</p>
<ol>
  <li>Indemnidad</li>
</ol>
<p>Mediante el  presente, el usuario conviene en que a su cargo corre la indemnización a  porcantidad , sus funcionarios, afiliados, sucesores, cesionarios, directores,  agentes, proveedores de servicios, prestadores y empleados, para mantenerlo  indemne de los reclamos o las demandas, con inclusión de los honorarios de los  letrados y las costas judiciales razonables, iniciados por terceros a raíz de o  bien con relación al contenido que el usuario entrega, anuncia o de otra forma  pone a disposición de otros a través del servicio, su uso del servicio, su  violación de las condiciones, o bien el incumplimiento de las declaraciones y  las garantías establecidas en el presente o la violación de los derechos de  otros.</p>
<ol>
  <li>Política anti-spam</li>
</ol>
<p>El usuario entiende  y conviene en que el envío de publicidad no solicitada a las direcciones de email  de porcantidad o a través de los sistemas de computación de porcantidad queda  expresamente prohibido por lo dispuesto en estas condiciones. Todo uso no  autorizado de los sistemas de computación de porcantidad representa una  violación a estas condiciones y a ciertas leyes nacionales y estaduales. Dichas  violaciones pueden someter al remitente o a sus representantes a multas civiles  y penales.</p>
<ol>
  <li>Límites y cancelación del servicio</li>
</ol>
<p>El usuario reconoce  que porcantidad puede poner límites respecto al uso del servicio, con  inclusión, entre otras cosas, de la cantidad máxima de días que el contenido  será retenido por el servicio, la cantidad y el tamaño máximo de los anuncios,  los mensajes de email, o de todo otro contenido que se puede transmitir o  almacenar a través del servicio, y la frecuencia con la cual el usuario puede  acceder al servicio. El usuario conviene en que porcantidad no es responsable  de la eliminación o el fracaso en el almacenamiento de aquel contenido que se  conserva o que se transmite a través del servicio. El usuario entiende que  porcantidad se reserva el derecho para, en todo momento, modificar o  interrumpir el servicio (o una parte de este) con o sin notificación, y que  porcantidad no será responsable ante el usuario ni ante un tercero por la  modificación, la suspensión o la interrupción del servicio. El usuario conviene  en que porcantidad, a su entera y sola discreción, tiene el derecho (pero no la  obligación) de eliminar o desactivar la cuenta del usuario, de bloquear su  dirección de email o ip, o bien de cualquier otra forma cancelar el acceso o el  uso del servicio (o parte de este) por parte del usuario, en forma inmediata y  sin notificación previa. Asimismo, porcantidad podrá quitar o descartar  contenido dentro el servicio, por cualquier motivo, con inclusión, no  restrictiva, del momento en que porcantidad considere que el usuario actuó en  forma contraria a la letra o el espíritu de las condiciones. Sumado a ello, el  usuario conviene en que porcantidad no será responsable ante el usuario mismo  ni ante un tercero por la cancelación del acceso del usuario al servicio.  Además, el usuario conviene en no intentar usar el servicio luego de la  cancelación por parte de porcantidad.</p>
<ol>
  <li>Alcance de los servicios de  porcantidad</li>
</ol>
<p>Este acuerdo no crea  ningún contrato de sociedad, de mandato, de franquicia, o relación laboral  entre porcantidad y el usuario. El usuario reconoce y acepta que porcantidad no  es parte en ninguna operación, ni tiene control alguno sobre la calidad,  seguridad o legalidad de los artículos anunciados, la veracidad o exactitud de  los anuncios, la capacidad de los usuarios para vender o comprar artículos.  Porcantidad no puede asegurar que un usuario completará una operación ni podrá  verificar la identidad o datos personales ingresados por los usuarios.  Porcantidad no garantiza la veracidad de la publicidad de terceros que aparezca  en el sitio y no será responsable por la correspondencia o contratos que el  usuario celebre con dichos terceros o con otros usuarios.</p>
<ol>
  <li>Fallas en el sistema</li>
</ol>
<p>Porcantidad no se  responsabiliza por cualquier daño, perjuicio o pérdida al usuario causados por  fallas en el sistema, en el servidor o en internet. Porcantidad tampoco será  responsable por cualquier virus que pudiera infectar el equipo del usuario como  consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier  transferencia de datos, archivos, imágenes, textos, o audio contenidos en el  mismo. Los usuarios no podrán imputarle responsabilidad alguna ni exigir pago  por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas  o fallas en los sistemas o en internet. Porcantidad no garantiza el acceso y  uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no  estar disponible debido a dificultades técnicas o fallas de internet, o por  cualquier otra circunstancia ajena a porcantidad; en tales casos se procurará  restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele  algún tipo de responsabilidad. Porcantidad no será responsable por ningún error  u omisión contenidos en su sitio web.</p>
<ol>
  <li>Habilidad para aceptar estas  condiciones de uso</li>
</ol>
<p>Usted afirma que o  es mayor de 18 años, o un menor emancipado o que posee permiso legal de sus  padres y/o tutor y que está completamente habilitado y competente para entrar  en estos términos, condiciones, obligaciones, afirmaciones, representaciones, y  garantías establecidas en estos términos, y para respetar y cumplir con estos  términos. </p>
<ol>
  <li>Información general</li>
</ol>
<p>Estas condiciones y  las demás políticas publicitadas en porcantidad constituyen el total y completo  entendimiento y todo lo acordado entre el usuario y porcantidad. Asimismo,  rigen el uso del servicio y prevalecen sobre todo previo entendimiento,  propuesta, acuerdo, negociación y discusión entre las partes, ya sea en forma  escrita o verbal. Las condiciones y la relación existente entre el usuario y  porcantidad se regirán por las leyes de la república argentina,  independientemente de las disposiciones sobre resolución de conflictos del  presente. El usuario y porcantidad convienen en someterse a la jurisdicción y  competencia personal y exclusiva de los tribunales de la capital federal  renunciando a cualquier otro tribunal que pudiera corresponder. La falta de  ejercicio o de exigencia de cumplimiento de parte de porcantidad de un derecho  o de una disposición de las condiciones no constituirá la renuncia a dicho  derecho o disposición. Si un tribunal competente resuelve la nulidad de una de  las disposiciones de las condiciones, las partes convienen en que el tribunal  deberá esforzarse por lograr que las intenciones de las partes tal como se  reflejan en la disposición y en las demás disposiciones de las condiciones  mantengan su efecto y vigencia. El usuario conviene en que sin importar las  prescripciones legales o leyes en contrario, los reclamos o las acciones que  surjan a partir o bien con relación al servicio o las condiciones de deben  iniciar dentro del año (1) luego de que el reclamo o bien la acción se originó,  de lo contrario, el derecho se considerará prescripto. Si la jurisdicción  exclusiva de los tribunales extranjeros no resultara aplicable por cualquier  motivo, el usuario acepta que toda controversia que el usuario desee plantear a  porcantidad con relación a estas condiciones, su existencia, validez,  calificación, interpretación, alcance, cumplimiento, o resolución, o sus  deberes o derechos relacionados con el mismo, o cualquier otra cuestión, se  resolverá definitivamente por el tribunal de arbitraje general de la bolsa de  comercio de la ciudad de buenos aires, argentina, de acuerdo con la  reglamentación vigente para el arbitraje que las partes declaran conocer y  aceptar.</p>
<ol>
  <li>Política de contenido</li>
</ol>
<p>A. Usted entiende  que porcantidad  no controla, y no es  responsable de todos los artículos, mensajes, comentarios, archivos, las  imágenes, las fotografías, los videos, sonidos y todo otro material  (&quot;contenido&quot;) anunciado o bien transmitido a través del servicio u  obtenido a partir de este, y que al utilizar el sitio usted puede estar  expuesto a contenido ofensivo, indecente, impreciso, tramposo o bien objetable  por algún otro motivo. Sumado a ello, el sitio porcantidad  y el contenido que se encuentra disponible a  través del sitio pueden contener enlaces a otros sitios, sitios que no guardan  relación alguna con porcantidad ni están bajo su control. Porcantidad no  realiza manifestaciones ni otorga garantías respecto de la precisión o la  autenticidad de la información contenida en dichos sitios. La conexión que el  usuario realice con otros sitios web queda totalmente bajo la responsabilidad  de dicho usuario. El usuario se obliga a evaluar y asumir los riesgos que se  relacionan con el uso del contenido. El usuario conviene en que puede no  confiar en dicho contenido y en que bajo ninguna circunstancia porcantidad será  responsable por el contenido o bien las pérdidas o los daños y perjuicios que  el usuario pueda sufrir como resultado del uso de un contenido publicado,  enviado por email o que de otra forma el usuario hubiera podido acceder  mediante el servicio. El usuario reconoce que porcantidad no hace un análisis  previo ni aprueba contenido alguno, no obstante lo cual, que porcantidad  conservará el derecho (pero no la obligación) a su entera discreción para  rechazar, eliminar o quitar aquel contenido que se haya puesto a disposición de  los demás a través del servicio y que implique una violación a la concepción  del sitio o las condiciones o por cualquier otro motivo.<br>
  B. Usted será único  responsable por todo contenido publicado, transmitido, o vinculado desde el  servicio y de las consecuencias de su publicación o de haberlo publicado. Más  específicamente, usted es el único responsable por todo el contenido que usted  suba, envíe por correo electrónico o haga disponible a través del servicio. Con  respecto al contenido publicado, transmitido, o vinculado desde el servicio por  usted, usted afirma, representa y/o garantiza que: (i) usted es dueño o tiene  las patentes necesarias, derechos, permisos, para usar y autorizar a  porcantidad a usar toda patente, marca registrada, secreto comercial, &ldquo;copyright&rdquo;  u otros derechos de propiedad en y a cualquier contenido permitiendo la  inclusión y el uso del contenido en la forma contemplada por el sitio y estos  términos; y (ii) usted tiene el consentimiento escrito y/o permiso de cada  persona individualmente identificada en el contenido para usar el nombre o  semejanza de cada uno de dichos individuos identificados; para permitir su  inclusión y uso del contenido en la manera contemplada por el sitio y estos  términos. Para clarificar, usted retiene todo los derechos de propiedad en su  contenido. Sin embargo, al enviar el contenido a porcantidad , usted le otorga  a porcantidad una licencia, global, libre de regalías, no exclusiva,  sublicenseable y transferible para usar, reproducir, distribuir, preparar  trabajos derivados de, exhibir y exponer, en todos los casos con cualquier  finalidad, formato, y dispositivo conocido o por conocerse, el contenido en  conexión con el sitio porcantidad y el negocio de porcantidad (y sus  sucesores), incluyendo la promoción y distribución de parte o todo el sitio de  porcantidad (y trabajos derivados) en  cualquier formato mediático y a través de cualquier canal mediático. Usted  también otorga a cada usuario del sitio de porcantidad una licencia no  exclusiva para acceder a su contenido a través de nuestro sitio. La licencia  que usted otorga expira una vez que usted remueve o borra el contenido del  sitio.<br>
  C. Porcantidad no  comparte ni apoya ningún contenido u opinión, recomendación, o consejo dado en  el sitio, y porcantidad expresamente niega cualquier y toda responsabilidad en  conexión con el contenido publicado por los usuarios del sitio. Porcantidad no  permite ninguna actividad de violación a los derechos de autor y/o de violación  de los derechos de propiedad intelectual en el sitio, y porcantidad si es  apropiadamente notificado removerá todo contenido que viole los derechos de  autor y/o de propiedad de un tercero. Porcantidad se reserva el derecho de  remover contenido sin previo aviso. Porcantidad bloqueara el acceso al sitio al  usuario que esté determinado en forma fehaciente que es un infractor  recurrente. Un infractor recurrente es un usuario que ha sido notificado de  estar violando uno y/o más de los términos más de 2 veces y/o que ha tenido  anuncios removidos del sitio en más de 2 ocasiones siempre que porcantidad  pueda determinar en forma fehaciente que se  trata de la misma persona. Porcantidad se reserva el derecho de decidir si el  contenido es apropiado y si cumple o no con los términos en lo que respecta a  otras violaciones no vinculadas a la violación de los derechos de autor y/o  propiedad intelectual, como ser por ejemplo pero no limitado a, pornografía,  obscenidad o material difamatorio, o de excesiva extensión. Porcantidad  se reserva la facultad de remover tal  contenido y/o quitarle al usuario la capacidad de subir dicho material que  viole los términos en cualquier momento, sin previo aviso y a su entera  discreción.</p>
<ol>
  <li>Jurisdicción y ley aplicable</li>
</ol>
<p>Este acuerdo estará  regido en todos sus puntos por las leyes vigentes en la república argentina.  Los procedimientos se llevarán a cabo en idioma castellano.</p>

				<div class="details col-md-9">
				</div>
			</div>
		</div>
		<div class="col-md-2"> &nbsp;</div>
	</div>
</div>
<?php echo $footer; ?>